remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Using Single Demonstration to Define Autonomous Manipulation Contact Task with Object Affordances"
description: "Supplemental Material"
show_downloads: false
